

[project]

name = "dummy"
version = "1.0.0"
description = "Hello CLI"
requires-python = ">=3.9",
dependencies = [
    "click>=3.8.1",
]


[project.scripts]


dummy = Google.click_tut:hello"


[build-system]


requires = ["flit_core<4"]
built-backend = "flit_core.buildapi"